// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STGeneticsPage.DBModel;

#nullable disable

namespace STGeneticsPage.Migrations
{
    [DbContext(typeof(AnimalContext))]
    [Migration("20230714024743_addData")]
    partial class addData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STGeneticsPage.DBModel.Animals", b =>
                {
                    b.Property<string>("AnimalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.ToTable("AnimalsT");

                    b.HasData(
                        new
                        {
                            AnimalId = "1c6b6c07-dc0f-401c-a24f-2b1dd5a2b7cb",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ButterCup",
                            Price = 4500,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "746c9918-5c72-4f5f-a470-7f189d18384a",
                            Breed = "Holstein",
                            DateOfBirth = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lola",
                            Price = 2000,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "3eb97735-38cf-40a3-aa2f-2ba2574f5c24",
                            Breed = "Limousin",
                            DateOfBirth = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thor",
                            Price = 5100,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "31a7b5eb-4e59-48be-96aa-41c06b4bf8b3",
                            Breed = "Piedmontese",
                            DateOfBirth = new DateTime(2012, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Delilah",
                            Price = 2000,
                            Sex = "Female",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "0ad48506-38d7-44c8-81c2-0c1dffbee40b",
                            Breed = "Brahman",
                            DateOfBirth = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Duke",
                            Price = 4600,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "5540c710-f517-4b25-bac8-486e19a835ea",
                            Breed = "Watusi",
                            DateOfBirth = new DateTime(2014, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Atlas",
                            Price = 2300,
                            Sex = "Male",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "49d6b945-1064-490d-9fe3-b3bd3fe1e943",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ginger",
                            Price = 2600,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "4219235b-d5b2-438d-8efe-b66b5eb76c7d",
                            Breed = "Charolais",
                            DateOfBirth = new DateTime(2019, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aurora",
                            Price = 6600,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "bb49a8c4-0b86-4370-a6aa-006205d64f34",
                            Breed = "Simmental",
                            DateOfBirth = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brutus",
                            Price = 6100,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "b59fd15f-d75c-4f72-b897-916d492cfd12",
                            Breed = "Hereford",
                            DateOfBirth = new DateTime(2011, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maverick",
                            Price = 1400,
                            Sex = "Male",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "6c238b1d-a75b-45ed-9f6c-dacaf3acfb46",
                            Breed = "Gelbvieh",
                            DateOfBirth = new DateTime(2010, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hazel",
                            Price = 900,
                            Sex = "Female",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "ce4ff762-dcc7-4aa2-9c86-a4c93d61d409",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2020, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Molly",
                            Price = 4700,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "c6c72693-4c9b-42e6-92ca-7148a5e60ef0",
                            Breed = "Watusi",
                            DateOfBirth = new DateTime(2017, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Titan",
                            Price = 6400,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "842de971-3d0a-473a-b1cc-524fe87376a3",
                            Breed = "Piedmontese",
                            DateOfBirth = new DateTime(2011, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bella",
                            Price = 1400,
                            Sex = "Female",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "8de9d525-3a8c-4164-8834-fc3caab0decd",
                            Breed = "Shorthorn",
                            DateOfBirth = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maisie",
                            Price = 2000,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "5c39c817-7d0f-4474-ad56-9ae47e390622",
                            Breed = "Gelbvieh",
                            DateOfBirth = new DateTime(2022, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maximus",
                            Price = 3200,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "a788828d-f243-40c8-94be-35dfb956e7e1",
                            Breed = "Simmental",
                            DateOfBirth = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rocky",
                            Price = 3000,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "6c3397f7-412e-451c-bdfc-e7db94886512",
                            Breed = "Limousin",
                            DateOfBirth = new DateTime(2021, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Clover",
                            Price = 3800,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "7c53ab9c-8a05-492d-942f-f255a549ca00",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2013, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daisy",
                            Price = 1500,
                            Sex = "Female",
                            Status = "Inactive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
