// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STGeneticsPage.DBModel;

#nullable disable

namespace STGeneticsPage.Migrations
{
    [DbContext(typeof(AnimalContext))]
    [Migration("20230714024644_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STGeneticsPage.DBModel.Animals", b =>
                {
                    b.Property<string>("AnimalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Breed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnimalId");

                    b.ToTable("AnimalsT");

                    b.HasData(
                        new
                        {
                            AnimalId = "40760cbe-aee9-4a2d-98ea-1b2d045f7e80",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2020, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ButterCup",
                            Price = 4500,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "5dff69da-bc64-46d2-ad11-7eaa49ef20ce",
                            Breed = "Holstein",
                            DateOfBirth = new DateTime(2022, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Lola",
                            Price = 2000,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "8cce5d2d-6db9-4e98-aceb-859ce546162e",
                            Breed = "Limousin",
                            DateOfBirth = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Thor",
                            Price = 5100,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "ac92da03-f94b-4936-8c8b-9700dc5b30f2",
                            Breed = "Piedmontese",
                            DateOfBirth = new DateTime(2012, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Delilah",
                            Price = 2000,
                            Sex = "Female",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "9706a3c5-9946-4d2f-ba41-232f7b1a2328",
                            Breed = "Brahman",
                            DateOfBirth = new DateTime(2020, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Duke",
                            Price = 4600,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "fd3bc03d-3263-4dab-b976-5a5b3a450f0f",
                            Breed = "Watusi",
                            DateOfBirth = new DateTime(2014, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Atlas",
                            Price = 2300,
                            Sex = "Male",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "715fd883-e3d7-4e63-9907-68e407780d0f",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ginger",
                            Price = 2600,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "83891bd2-a3cc-48cf-9e6a-0727f67b671c",
                            Breed = "Charolais",
                            DateOfBirth = new DateTime(2019, 4, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Aurora",
                            Price = 6600,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "6aa56b8a-9337-4b18-b4b5-c23b543a7fd1",
                            Breed = "Simmental",
                            DateOfBirth = new DateTime(2018, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brutus",
                            Price = 6100,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "17180121-f6bc-412e-9ab0-98c7aed3f5a6",
                            Breed = "Hereford",
                            DateOfBirth = new DateTime(2011, 10, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maverick",
                            Price = 1400,
                            Sex = "Male",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "24fbca3a-305c-4e66-b307-49dc0360044f",
                            Breed = "Gelbvieh",
                            DateOfBirth = new DateTime(2010, 6, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Hazel",
                            Price = 900,
                            Sex = "Female",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "9530a454-996f-4fd6-8ea6-ee0e51360456",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2020, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Molly",
                            Price = 4700,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "6a78857b-71b0-45d7-b6e4-615c83cb2a77",
                            Breed = "Watusi",
                            DateOfBirth = new DateTime(2017, 5, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Titan",
                            Price = 6400,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "4597d205-64df-42f7-9fef-44e1303e1db8",
                            Breed = "Piedmontese",
                            DateOfBirth = new DateTime(2011, 3, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bella",
                            Price = 1400,
                            Sex = "Female",
                            Status = "Inactive"
                        },
                        new
                        {
                            AnimalId = "82c27db8-8b9f-4987-b22d-f17fda9bc579",
                            Breed = "Shorthorn",
                            DateOfBirth = new DateTime(2023, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maisie",
                            Price = 2000,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "d2ec1d4c-0892-4a5d-8795-01508f7d3a3e",
                            Breed = "Gelbvieh",
                            DateOfBirth = new DateTime(2022, 12, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maximus",
                            Price = 3200,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "8e246acf-b6c2-430a-8773-5beddf888069",
                            Breed = "Simmental",
                            DateOfBirth = new DateTime(2022, 8, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Rocky",
                            Price = 3000,
                            Sex = "Male",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "94c7a75b-4aff-4ef0-9b75-240c08b91309",
                            Breed = "Limousin",
                            DateOfBirth = new DateTime(2021, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Clover",
                            Price = 3800,
                            Sex = "Female",
                            Status = "Active"
                        },
                        new
                        {
                            AnimalId = "4cc857b0-7837-4a61-9808-ed7708898258",
                            Breed = "Red Angus",
                            DateOfBirth = new DateTime(2013, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Daisy",
                            Price = 1500,
                            Sex = "Female",
                            Status = "Inactive"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
